spring.application.name=app_smart_4.0

server.port=8088
spring.datasource.url=jdbc:mysql://localhost:3306/DB_SMART_4_0
spring.datasource.username=root
spring.datasource.password=senai
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
